attack:
  NES:
    lr: 2.55
  epsilon: 25.5
  max_loss_queries: 10000
  name: NES
  p: linf
  test_sample: 1000
dataset:
  name: CIFAR10
  normalize: false
defense:
  blacklight: false
  sigma: 0.0
device: cuda:1
model:
  init_mode: kaiming_fan_out
  name: resnet
  normalize_layer: true
  resnet:
    block_type: basic
    depth: 110
    initial_channels: 16
  type: cifar
test:
  batch_size: 1
  checkpoint: experiments/AT_cifar10/resnet_linf/exp00/checkpoint_00160.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/cifar10_AT/untargeted/linf/score/resnet/NES/
