attack:
  epsilon: 1275.0
  max_loss_queries: 10000
  name: Opt
  p: l2
  test_sample: 1000
dataset:
  name: CIFAR100
  normalize: false
defense:
  blacklight: false
  sigma: 0.02
device: cuda:3
model:
  init_mode: kaiming_fan_out
  name: vgg
  normalize_layer: true
  type: cifar
  vgg:
    n_channels:
    - 64
    - 128
    - 256
    - 512
    - 512
    n_layers:
    - 2
    - 2
    - 3
    - 3
    - 3
    use_bn: true
test:
  batch_size: 1
  checkpoint: experiments/cifar100/vgg/exp00/checkpoint_00160.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/cifar100_RAND/untargeted/l2/decision/vgg/Opt/
