name: certifiedattack
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.9
  
  # PyTorch and related
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio
  - pytorch-cuda=12.1  # Adjust based on your CUDA version
  
  # Scientific computing
  - numpy>=1.21.0
  - scipy=1.11.0
  - matplotlib>=3.5.0
  - statsmodels>=0.13.0
  
  # Progress bars and utilities
  - tqdm>=4.62.0
  
  # Development tools
  - pip
  - jupyter
  - ipython
  
  # Install remaining packages via pip
  - pip:
    # Core dependencies
    - fvcore>=0.1.5
    - thop>=0.1.0
    - tensorboard>=2.7.0
    
    # For Certified Attacks
    - einops>=0.6.0
    - transformers>=4.20.0
    - accelerate>=0.20.0
    - pytorch_fid>=0.3.0
    - ema-pytorch>=0.2.0
    - torchviz>=0.0.2
    
    # Optional development dependencies
    - pytest>=7.0.0
    - black>=22.0.0
    - flake8>=4.0.0
    - pre-commit>=2.17.0