attack:
  epsilon: 25.5
  max_loss_queries: 10000
  name: RayS
  p: linf
  test_sample: 1000
dataset:
  name: CIFAR100
  normalize: false
defense:
  blacklight: false
  sigma: 0.0
device: cuda:3
model:
  init_mode: kaiming_fan_out
  name: resnet
  normalize_layer: true
  resnet:
    block_type: basic
    depth: 110
    initial_channels: 16
  type: cifar
test:
  batch_size: 1
  checkpoint: experiments/AT_cifar100/resnet_linf/exp00/checkpoint_00160.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/cifar100_AT/untargeted/linf/decision/resnet/RayS/
