attack:
  GeoDA:
    sub_dim: 30
  epsilon: 25.5
  max_loss_queries: 10000
  name: GeoDA
  p: linf
  test_sample: 1000
dataset:
  name: CIFAR100
  normalize: false
defense:
  blacklight: false
  sigma: 0.02
device: cuda:0
model:
  init_mode: kaiming_fan_out
  name: resnext
  normalize_layer: true
  resnext:
    base_channels: 64
    cardinality: 8
    depth: 29
    initial_channels: 64
  type: cifar
test:
  batch_size: 1
  checkpoint: experiments/cifar100/resnext/exp00/checkpoint_00300.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/cifar100_RAND/untargeted/linf/decision/resnext/GeoDA/
