device: cuda:0
defense:
  blacklight: False
  sigma: 0.0
  post_sigma: 0.0
attack:
  name: CertifiedAttack
  epsilon: 0.0
  p: unrestricted
  max_loss_queries: 100000
  test_sample: 1000
  CertifiedAttack:
    initialization: random
    shifting: geo
    pdf_args: [-1,0.25]
    p: 0.90
    diffusion: False
    MonteNum: 1000
    query_batch: 1000
test:
  checkpoint: 'experiments/cifar10/resnet/exp00/checkpoint_00160.pth'
  output_dir: 'experiments/attack/CA_ablation/CA_binary_nolocal'
  batch_size: 1
  dataloader:
    num_workers: 2
    pin_memory: False
dataset:
  name: CIFAR10
  normalize: False
model:
  type: cifar
  name: resnet
  init_mode: kaiming_fan_out
  resnet:
    depth: 110
    initial_channels: 16
    block_type: basic
  normalize_layer: True


