attack:
  CertifiedAttack:
    diffusion: false
    initialization: smt_ssp
    p: 0.1
    pdf_args:
    - -1
    - 0.025
  epsilon: 0.0
  max_loss_queries: 1000
  name: CertifiedAttack
  p: unrestricted
  test_sample: 1000
dataset:
  image_size: 224
  n_channels: 3
  n_classes: 1000
  name: ImageNet
  normalize: false
defense:
  blacklight: false
  sigma: 0.02
device: cuda:0
model:
  init_mode: kaiming_fan_out
  name: resnet
  normalize_layer: true
  resnet:
    block_type: basic
    initial_channels: 64
    n_blocks:
    - 2
    - 2
    - 2
    - 2
  type: imagenet
test:
  batch_size: 1
  checkpoint: experiments/imagenet/resnet18/exp00/checkpoint_00090.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/imagenet_RAND/untargeted/unrestricted/decision/resnet/CA_sssp/
