attack:
  CertifiedAttack:
    diffusion: false
    initialization: bin_search
    p: 0.1
    pdf_args:
    - -1
    - 0.025
  epsilon: 0.0
  max_loss_queries: 1000
  name: CertifiedAttack
  p: unrestricted
  test_sample: 1000
dataset:
  image_size: 224
  n_channels: 3
  n_classes: 1000
  name: ImageNet
  normalize: false
defense:
  blacklight: false
  post_sigma: 0.0
  sigma: 0.02
device: cuda:0
model:
  init_mode: kaiming_fan_out
  name: vgg
  normalize_layer: true
  type: imagenet
  vgg:
    n_channels:
    - 64
    - 128
    - 256
    - 512
    - 512
    n_layers:
    - 2
    - 2
    - 3
    - 3
    - 3
    use_bn: true
test:
  batch_size: 1
  checkpoint: experiments/imagenet/vgg16/exp00/checkpoint_00090.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/imagenet_RAND/untargeted/unrestricted/decision/vgg/CA/
