attack:
  epsilon: 1275.0
  max_loss_queries: 10000
  name: Simple
  p: l2
  test_sample: 1000
dataset:
  name: CIFAR10
  normalize: false
defense:
  blacklight: true
  sigma: 0.0
device: cuda:3
model:
  init_mode: kaiming_fan_out
  name: resnext
  normalize_layer: true
  resnext:
    base_channels: 64
    cardinality: 8
    depth: 29
    initial_channels: 64
  type: cifar
test:
  batch_size: 1
  checkpoint: experiments/cifar10/resnext/exp00/checkpoint_00300.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/cifar10_blacklight/untargeted/l2/score/resnext/Simple/
