attack:
  GeoDA:
    sub_dim: 30
  epsilon: 25.5
  max_loss_queries: 10000
  name: GeoDA
  p: linf
  test_sample: 1000
dataset:
  name: CIFAR100
  normalize: false
defense:
  blacklight: false
  post_sigma: 0.2
  sigma: 0.0
device: cuda:0
model:
  init_mode: kaiming_fan_out
  name: wrn
  normalize_layer: true
  type: cifar
  wrn:
    depth: 28
    drop_rate: 0.0
    initial_channels: 16
    widening_factor: 10
test:
  batch_size: 1
  checkpoint: experiments/cifar100/wrn/exp00/checkpoint_00200.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/cifar100_post_RAND/untargeted/linf/decision/wrn/GeoDA/
