attack:
  epsilon: 25.5
  max_loss_queries: 10000
  name: Bandit
  p: linf
  test_sample: 1000
dataset:
  name: CIFAR10
  normalize: false
defense:
  blacklight: false
  post_sigma: 0.2
  sigma: 0.0
device: cuda:0
model:
  init_mode: kaiming_fan_out
  name: resnet
  normalize_layer: true
  resnet:
    block_type: basic
    depth: 110
    initial_channels: 16
  type: cifar
test:
  batch_size: 1
  checkpoint: experiments/cifar10/resnet/exp00/checkpoint_00160.pth
  dataloader:
    num_workers: 2
    pin_memory: false
  output_dir: experiments/attack/cifar10_post_RAND/untargeted/linf/score/resnet/Bandit/
